# Generated by Django 2.2.17 on 2020-11-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MOVEIS', 'moveis'), ('DECORACAO', 'decoracao'), ('CELULAR', 'celular'), ('INFORMATICA', 'informatica'), ('BRINQUEDOS', 'brinquedos')], max_length=50)),
            ],
        ),
    ]
