# Generated by Django 2.2.17 on 2020-11-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_foreingdoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForeingDoc',
        ),
    ]
